#!/usr/bin/env bash
### pool -- command-line util to manage pools
### Usage: pool <command> [<args>]
###    or: pool help <command>
###
### Manage Tinlake pools the good old fashioned way
###

export POOL_BASE_DIR="${POOL_BASE_DIR:-"$(cd "${0%/*}"&&pwd)/../.."}"
set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help -- "$1"
elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

"${0##*/}-${1-help}" "${@:2}"
