#!/usr/bin/env bash
### pool-help -- print help about pool(1) or one of its subcommands
### Usage: pool help [<command>]

BUGS=https://github.com/centrifuge/tinlake-pools-cli

name=pool
cmd=${1##*-}
file=${0%-help}${1+-$cmd}
header=$(perl -ne 'print "$2\n" if /^(\S)\1\1(?: (.*))?/' "$file")

if ! [[ $header ]]; then
  sed "s/^/${0##*/}: /" "$file"
elif [[ $(wc -l <<<"$header") = 1 ]]; then
  echo "$header"
else
  sed "1{/^$name\\S* -- /d;}" <<<"$header"
fi

[[ $1 ]] && exit

for file in "${0%/*}"/"$name"-*; do
  if [[ -L $file ]]; then
    continue
  elif [[ $file = */$name---* ]]; then
    special_commands+=("$file")
  else
    normal_commands+=("$file")
  fi
done

list-commands() {
  cat "$@" |
  perl -ne 'print "$2 $3\n" if /^(\S)\1\1 '"$name"'-(\S+) -- (.*)/' |
  while read -r name label; do
    printf "   %-14s  %s\\n" "$name" "$label"
  done | LANG=C sort
}

cat <<.

Commands:

$(list-commands "${normal_commands[@]}")


Configuration Variables:

ETH_CHAIN
    Current active eth chain (ethlive, kovan), set
    this to avoid delay introduced by \`seth chain\`

POOL_BASE_DIR
    Path to local pool metadata. Used for the registry updates.
    Defaults to \`pwd\`

POOL_REGISTRY_ADDR
    Address of the registry contract for the specific environment

Report bugs to <$BUGS>.
.
