#!/usr/bin/env node
/// pool-status -- print a short summary for all known pools
/// Usage: pool status
///

const fs = require('fs')
const execSync = require('child_process').execSync
const fetch = require('node-fetch')
const multicall = require('@makerdao/multicall')
const BigNumber = require('bignumber.js')
const registryAddr = process.env['POOL_REGISTRY_ADDRESS']

let poolConfig = JSON.parse(execSync('pool data').toString())
let pools = Object.keys(poolConfig).reduce((l, p) => {
  p = poolConfig[p]
  if (p.version < 3 || !p.addresses || !p.addresses.ROOT_CONTRACT) return l
  let addr = p.addresses

  let data = {
      name: p.metadata.name,
      root: addr.ROOT_CONTRACT,
      juniorTranche: addr.JUNIOR_TRANCHE,
      seniorTranche: addr.SENIOR_TRANCHE,
      juniorToken: addr.JUNIOR_TOKEN,
      seniorToken: addr.SENIOR_TOKEN,
      assessor: addr.ASSESSOR,
      reserve: addr.RESERVE,
      feed: addr.FEED,
  }
  l[data.root] = data
  return l
}, {})

let calls = []
Object.values(pools).forEach(p => {
    calls.push({
      target: p.juniorTranche,
      call: ['totalSupply()(uint)'],
      returns: [[`${p.root}-juniorSupply`, val => val ]]
    })
    calls.push({
      target: p.juniorTranche,
      call: ['totalRedeem()(uint)'],
      returns: [[`${p.root}-juniorRedeem`, val => val ]]
    })
    calls.push({
      target: p.seniorTranche,
      call: ['totalSupply()(uint)'],
      returns: [[`${p.root}-seniorSupply`, val => val ]]
    })
    calls.push({
      target: p.seniorTranche,
      call: ['totalRedeem()(uint)'],
      returns: [[`${p.root}-seniorRedeem`, val => val ]]
    })
    calls.push({
      target: p.assessor,
      call: ['calcTokenPrices()(uint, uint)'],
      returns: [
        [`${p.root}-juniorTokenPrice`, val => val ],
        [`${p.root}-seniorTokenPrice`, val => val ],
    ]})
    calls.push({
      target: p.seniorToken,
      call: ['totalSupply()(uint)'],
      returns: [
        [`${p.root}-seniorTotalSupply`, val => val ],
    ]})
    calls.push({
      target: p.juniorToken,
      call: ['totalSupply()(uint)'],
      returns: [
        [`${p.root}-juniorTotalSupply`, val => val ],
    ]})
    calls.push({
      target: p.reserve,
      call: ['totalBalance()(uint)'],
      returns: [
        [`${p.root}-reserveTotalBalance`, val => val ],
    ]})
    calls.push({
      target: p.feed,
      call: ['currentNAV()(uint)'],
      returns: [
        [`${p.root}-feedCurrentNAV`, val => val ],
    ]})

})

let config = {
  multicallAddress: process.env['MULTICALL_ADDR'],
  rpcUrl: process.env['ETH_RPC_URL']
}

const watcher = multicall.createWatcher(calls, config);


let weiToDecimal = (num) => { return new BigNumber(num.toString()).div(new BigNumber('1000000000000000000')) }

let rayToDecimal = (num) => { return new BigNumber(num.toString()).div(new BigNumber('1000000000000000000000000000')) }


let formatWeiNum = (num) => {
  return formatNum(weiToDecimal(num))}

let formatNum = (num, decimals) => {
  decimals = decimals ? decimals : 2
  return num.toFormat(decimals, {
    decimalSeparator: '.',
    groupSeparator: ',',
    groupSize: 3,})
}

let printInYellow = (txt) => console.log("\x1b[33m%s\x1b[0m", txt)

let printPoolDetails = (pool) => {
  console.log(`${pool.name} (${pool.root})`)

  let reserveRatio = new BigNumber(pool.reserveTotalBalance).div(new BigNumber(pool.reserveTotalBalance).plus(new BigNumber(pool.feedCurrentNAV))).times(new BigNumber('100'))
  let juniorValue = rayToDecimal(pool.juniorTokenPrice).times(weiToDecimal(pool.juniorTotalSupply))
  let seniorValue = rayToDecimal(pool.seniorTokenPrice).times(weiToDecimal(pool.seniorTotalSupply))


  console.log(`Cash Drag: ${formatNum(reserveRatio)}% Reserve: ${formatWeiNum(pool.reserveTotalBalance)} NAV: ${formatWeiNum(pool.feedCurrentNAV)}`)
  console.log(`Junior: DAI ${formatNum(juniorValue)} (Price ${formatNum(rayToDecimal(pool.juniorTokenPrice), 4)}) - Senior: DAI ${formatNum(seniorValue)} (Price:  ${formatNum(rayToDecimal(pool.seniorTokenPrice), 4)})`)

  if (pool.juniorSupply > 0 || pool.juniorRedeem > 0) {
    printInYellow(`Junior Supply: ${formatWeiNum(pool.juniorSupply)} Redeem: ${formatWeiNum(pool.juniorRedeem)}`)
  }

  if (pool.seniorSupply > 0 || pool.seniorRedeem > 0) {
    printInYellow(`Senior Supply: ${formatWeiNum(pool.seniorSupply)} Redeem: ${formatWeiNum(pool.seniorRedeem)}`)
  }
  console.log('-'.repeat(80))
}

watcher.subscribe(update => {
  let event = update.type.split('-')
  pools[event[0]][event[1]] = update.value
});


watcher.start().then(function () {
  Object.values(pools).forEach(printPoolDetails)
  process.exit()
}).catch(err => {
  console.error(err)
  process.exit(1)
})

