#!/usr/bin/env bash
#!/usr/bin/env bash
### registry -- command-line util to manage pool metadata
### Usage: pool registry <command> [<args>]
###    or: pool registry help <command>
###
### Update pool metadata on chain and on IPFS
###

export BASE_DIR="${BASE_DIR:-"$(cd "${0%/*}"&&pwd)/../../.."}"
export POOL_CONFIG="${POOL_CONFIG:-"$BASE_DIR/config.json"}"

set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help -- "$1"
elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

"${0##*/}-${1-help}" "${@:2}"
